# Generated by Django 5.0.9 on 2025-11-07 14:43

import django.utils.timezone
import model_utils.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='App',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(editable=False, max_length=100, unique=True)),
                ('label', models.CharField(editable=False, max_length=100)),
                ('verbose_name', models.CharField(max_length=100)),
                ('url', models.CharField(blank=True, editable=False, max_length=200, null=True)),
                ('icon', models.CharField(blank=True, editable=False, max_length=200, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False)),
                ('is_service', models.BooleanField(default=False)),
                ('description', models.CharField(blank=True, editable=False, max_length=255, null=True)),
                ('permissions', models.ManyToManyField(editable=False, related_name='apps', to='auth.permission')),
            ],
            options={
                'verbose_name': 'App',
                'verbose_name_plural': 'apps',
                'ordering': ['name'],
            },
        ),
    ]
